version: "3"
services:
  postgres_db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres_data:/var/lib/postgresql
volumes:
  postgres_data: ~
