/* tslint:disable */
/* eslint-disable */
//  This file was automatically generated and should not be edited.

export type CreateUserInput = {
  id?: string | null,
  email: string,
  firstName: string,
  lastName: string,
  phone: string,
  role: UserRole,
  status: UserStatus,
};

export enum UserRole {
  EMPLOYEE = "EMPLOYEE",
  MANAGER = "MANAGER",
  ADMIN = "ADMIN",
}


export enum UserStatus {
  PENDING = "PENDING",
  ACTIVE = "ACTIVE",
  DISABLED = "DISABLED",
}


export type ModelUserConditionInput = {
  email?: ModelStringInput | null,
  firstName?: ModelStringInput | null,
  lastName?: ModelStringInput | null,
  phone?: ModelStringInput | null,
  role?: ModelUserRoleInput | null,
  status?: ModelUserStatusInput | null,
  and?: Array< ModelUserConditionInput | null > | null,
  or?: Array< ModelUserConditionInput | null > | null,
  not?: ModelUserConditionInput | null,
};

export type ModelStringInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  size?: ModelSizeInput | null,
};

export enum ModelAttributeTypes {
  binary = "binary",
  binarySet = "binarySet",
  bool = "bool",
  list = "list",
  map = "map",
  number = "number",
  numberSet = "numberSet",
  string = "string",
  stringSet = "stringSet",
  _null = "_null",
}


export type ModelSizeInput = {
  ne?: number | null,
  eq?: number | null,
  le?: number | null,
  lt?: number | null,
  ge?: number | null,
  gt?: number | null,
  between?: Array< number | null > | null,
};

export type ModelUserRoleInput = {
  eq?: UserRole | null,
  ne?: UserRole | null,
};

export type ModelUserStatusInput = {
  eq?: UserStatus | null,
  ne?: UserStatus | null,
};

export type UpdateUserInput = {
  id: string,
  email?: string | null,
  firstName?: string | null,
  lastName?: string | null,
  phone?: string | null,
  role?: UserRole | null,
  status?: UserStatus | null,
  expectedVersion: number,
};

export type DeleteUserInput = {
  id?: string | null,
  expectedVersion: number,
};

export type CreateClientInput = {
  id?: string | null,
  clientNumber: string,
  name: string,
  contact: string,
  phone: string,
  address: string,
  province?: string | null,
  city: string,
  postalCode: string,
  email: string,
  owners?: Array< string | null > | null,
  status?: string | null,
};

export type ModelClientConditionInput = {
  clientNumber?: ModelStringInput | null,
  name?: ModelStringInput | null,
  contact?: ModelStringInput | null,
  phone?: ModelStringInput | null,
  address?: ModelStringInput | null,
  province?: ModelStringInput | null,
  city?: ModelStringInput | null,
  postalCode?: ModelStringInput | null,
  email?: ModelStringInput | null,
  owners?: ModelStringInput | null,
  status?: ModelStringInput | null,
  and?: Array< ModelClientConditionInput | null > | null,
  or?: Array< ModelClientConditionInput | null > | null,
  not?: ModelClientConditionInput | null,
};

export type UpdateClientInput = {
  id: string,
  clientNumber?: string | null,
  name?: string | null,
  contact?: string | null,
  phone?: string | null,
  address?: string | null,
  province?: string | null,
  city?: string | null,
  postalCode?: string | null,
  email?: string | null,
  owners?: Array< string | null > | null,
  status?: string | null,
  expectedVersion: number,
};

export type DeleteClientInput = {
  id?: string | null,
  expectedVersion: number,
};

export type CreateContractInput = {
  clientID: string,
  type: string,
  startDate?: string | null,
  endDate?: string | null,
  gst?: string | null,
  qst?: string | null,
  period?: string | null,
  corporation?: boolean | null,
  corporationYearEndDate?: string | null,
  payrollNumber?: string | null,
  payrollFrequency?: string | null,
  remittancePeriod?: string | null,
  remittancePeriodQc?: string | null,
  cheques?: number | null,
  wsib?: string | null,
  wsibRemittance?: string | null,
  wsibRate?: string | null,
  wsibCode?: string | null,
  csst?: string | null,
  csstRemittance?: string | null,
  csstRate?: string | null,
  csstCode?: string | null,
  t4Deadline?: string | null,
};

export type ModelContractConditionInput = {
  startDate?: ModelStringInput | null,
  endDate?: ModelStringInput | null,
  gst?: ModelStringInput | null,
  qst?: ModelStringInput | null,
  period?: ModelStringInput | null,
  corporation?: ModelBooleanInput | null,
  corporationYearEndDate?: ModelStringInput | null,
  payrollNumber?: ModelStringInput | null,
  payrollFrequency?: ModelStringInput | null,
  remittancePeriod?: ModelStringInput | null,
  remittancePeriodQc?: ModelStringInput | null,
  cheques?: ModelIntInput | null,
  wsib?: ModelStringInput | null,
  wsibRemittance?: ModelStringInput | null,
  wsibRate?: ModelStringInput | null,
  wsibCode?: ModelStringInput | null,
  csst?: ModelStringInput | null,
  csstRemittance?: ModelStringInput | null,
  csstRate?: ModelStringInput | null,
  csstCode?: ModelStringInput | null,
  t4Deadline?: ModelStringInput | null,
  and?: Array< ModelContractConditionInput | null > | null,
  or?: Array< ModelContractConditionInput | null > | null,
  not?: ModelContractConditionInput | null,
};

export type ModelBooleanInput = {
  ne?: boolean | null,
  eq?: boolean | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
};

export type ModelIntInput = {
  ne?: number | null,
  eq?: number | null,
  le?: number | null,
  lt?: number | null,
  ge?: number | null,
  gt?: number | null,
  between?: Array< number | null > | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
};

export type UpdateContractInput = {
  clientID: string,
  type: string,
  startDate?: string | null,
  endDate?: string | null,
  gst?: string | null,
  qst?: string | null,
  period?: string | null,
  corporation?: boolean | null,
  corporationYearEndDate?: string | null,
  payrollNumber?: string | null,
  payrollFrequency?: string | null,
  remittancePeriod?: string | null,
  remittancePeriodQc?: string | null,
  cheques?: number | null,
  wsib?: string | null,
  wsibRemittance?: string | null,
  wsibRate?: string | null,
  wsibCode?: string | null,
  csst?: string | null,
  csstRemittance?: string | null,
  csstRate?: string | null,
  csstCode?: string | null,
  t4Deadline?: string | null,
  expectedVersion: number,
};

export type DeleteContractInput = {
  clientID: string,
  type: string,
  expectedVersion: number,
};

export type CreateJobInput = {
  id?: string | null,
  clientID: string,
  type: string,
  deadline: string,
  assigneeID?: string | null,
};

export type ModelJobConditionInput = {
  clientID?: ModelIDInput | null,
  type?: ModelStringInput | null,
  deadline?: ModelStringInput | null,
  assigneeID?: ModelIDInput | null,
  and?: Array< ModelJobConditionInput | null > | null,
  or?: Array< ModelJobConditionInput | null > | null,
  not?: ModelJobConditionInput | null,
};

export type ModelIDInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  size?: ModelSizeInput | null,
};

export type UpdateJobInput = {
  id: string,
  clientID?: string | null,
  type?: string | null,
  deadline?: string | null,
  assigneeID?: string | null,
  expectedVersion: number,
};

export type DeleteJobInput = {
  id?: string | null,
  expectedVersion: number,
};

export type ModelUserFilterInput = {
  id?: ModelIDInput | null,
  email?: ModelStringInput | null,
  firstName?: ModelStringInput | null,
  lastName?: ModelStringInput | null,
  phone?: ModelStringInput | null,
  role?: ModelUserRoleInput | null,
  status?: ModelUserStatusInput | null,
  and?: Array< ModelUserFilterInput | null > | null,
  or?: Array< ModelUserFilterInput | null > | null,
  not?: ModelUserFilterInput | null,
};

export type ModelClientFilterInput = {
  id?: ModelIDInput | null,
  clientNumber?: ModelStringInput | null,
  name?: ModelStringInput | null,
  contact?: ModelStringInput | null,
  phone?: ModelStringInput | null,
  address?: ModelStringInput | null,
  province?: ModelStringInput | null,
  city?: ModelStringInput | null,
  postalCode?: ModelStringInput | null,
  email?: ModelStringInput | null,
  owners?: ModelStringInput | null,
  status?: ModelStringInput | null,
  and?: Array< ModelClientFilterInput | null > | null,
  or?: Array< ModelClientFilterInput | null > | null,
  not?: ModelClientFilterInput | null,
};

export type ModelStringKeyConditionInput = {
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
};

export type ModelContractFilterInput = {
  clientID?: ModelIDInput | null,
  type?: ModelStringInput | null,
  startDate?: ModelStringInput | null,
  endDate?: ModelStringInput | null,
  gst?: ModelStringInput | null,
  qst?: ModelStringInput | null,
  period?: ModelStringInput | null,
  corporation?: ModelBooleanInput | null,
  corporationYearEndDate?: ModelStringInput | null,
  payrollNumber?: ModelStringInput | null,
  payrollFrequency?: ModelStringInput | null,
  remittancePeriod?: ModelStringInput | null,
  remittancePeriodQc?: ModelStringInput | null,
  cheques?: ModelIntInput | null,
  wsib?: ModelStringInput | null,
  wsibRemittance?: ModelStringInput | null,
  wsibRate?: ModelStringInput | null,
  wsibCode?: ModelStringInput | null,
  csst?: ModelStringInput | null,
  csstRemittance?: ModelStringInput | null,
  csstRate?: ModelStringInput | null,
  csstCode?: ModelStringInput | null,
  t4Deadline?: ModelStringInput | null,
  and?: Array< ModelContractFilterInput | null > | null,
  or?: Array< ModelContractFilterInput | null > | null,
  not?: ModelContractFilterInput | null,
};

export enum ModelSortDirection {
  ASC = "ASC",
  DESC = "DESC",
}


export type ModelJobFilterInput = {
  id?: ModelIDInput | null,
  clientID?: ModelIDInput | null,
  type?: ModelStringInput | null,
  deadline?: ModelStringInput | null,
  assigneeID?: ModelIDInput | null,
  and?: Array< ModelJobFilterInput | null > | null,
  or?: Array< ModelJobFilterInput | null > | null,
  not?: ModelJobFilterInput | null,
};

export type CreateUserMutationVariables = {
  input: CreateUserInput,
  condition?: ModelUserConditionInput | null,
};

export type CreateUserMutation = {
  createUser:  {
    __typename: "User",
    id: string,
    email: string,
    firstName: string,
    lastName: string,
    phone: string,
    role: UserRole,
    status: UserStatus,
    createdAt: string,
    updatedAt: string,
    version: number,
  } | null,
};

export type UpdateUserMutationVariables = {
  input: UpdateUserInput,
  condition?: ModelUserConditionInput | null,
};

export type UpdateUserMutation = {
  updateUser:  {
    __typename: "User",
    id: string,
    email: string,
    firstName: string,
    lastName: string,
    phone: string,
    role: UserRole,
    status: UserStatus,
    createdAt: string,
    updatedAt: string,
    version: number,
  } | null,
};

export type DeleteUserMutationVariables = {
  input: DeleteUserInput,
  condition?: ModelUserConditionInput | null,
};

export type DeleteUserMutation = {
  deleteUser:  {
    __typename: "User",
    id: string,
    email: string,
    firstName: string,
    lastName: string,
    phone: string,
    role: UserRole,
    status: UserStatus,
    createdAt: string,
    updatedAt: string,
    version: number,
  } | null,
};

export type CreateClientMutationVariables = {
  input: CreateClientInput,
  condition?: ModelClientConditionInput | null,
};

export type CreateClientMutation = {
  createClient:  {
    __typename: "Client",
    id: string,
    clientNumber: string,
    name: string,
    contact: string,
    phone: string,
    address: string,
    province: string | null,
    city: string,
    postalCode: string,
    email: string,
    owners: Array< string | null > | null,
    status: string | null,
    contracts:  {
      __typename: "ModelContractConnection",
      items:  Array< {
        __typename: "Contract",
        clientID: string,
        type: string,
        startDate: string | null,
        endDate: string | null,
        gst: string | null,
        qst: string | null,
        period: string | null,
        corporation: boolean | null,
        corporationYearEndDate: string | null,
        payrollNumber: string | null,
        payrollFrequency: string | null,
        remittancePeriod: string | null,
        remittancePeriodQc: string | null,
        cheques: number | null,
        wsib: string | null,
        wsibRemittance: string | null,
        wsibRate: string | null,
        wsibCode: string | null,
        csst: string | null,
        csstRemittance: string | null,
        csstRate: string | null,
        csstCode: string | null,
        t4Deadline: string | null,
        createdAt: string,
        updatedAt: string,
        version: number,
      } | null > | null,
      nextToken: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
    version: number,
  } | null,
};

export type UpdateClientMutationVariables = {
  input: UpdateClientInput,
  condition?: ModelClientConditionInput | null,
};

export type UpdateClientMutation = {
  updateClient:  {
    __typename: "Client",
    id: string,
    clientNumber: string,
    name: string,
    contact: string,
    phone: string,
    address: string,
    province: string | null,
    city: string,
    postalCode: string,
    email: string,
    owners: Array< string | null > | null,
    status: string | null,
    contracts:  {
      __typename: "ModelContractConnection",
      items:  Array< {
        __typename: "Contract",
        clientID: string,
        type: string,
        startDate: string | null,
        endDate: string | null,
        gst: string | null,
        qst: string | null,
        period: string | null,
        corporation: boolean | null,
        corporationYearEndDate: string | null,
        payrollNumber: string | null,
        payrollFrequency: string | null,
        remittancePeriod: string | null,
        remittancePeriodQc: string | null,
        cheques: number | null,
        wsib: string | null,
        wsibRemittance: string | null,
        wsibRate: string | null,
        wsibCode: string | null,
        csst: string | null,
        csstRemittance: string | null,
        csstRate: string | null,
        csstCode: string | null,
        t4Deadline: string | null,
        createdAt: string,
        updatedAt: string,
        version: number,
      } | null > | null,
      nextToken: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
    version: number,
  } | null,
};

export type DeleteClientMutationVariables = {
  input: DeleteClientInput,
  condition?: ModelClientConditionInput | null,
};

export type DeleteClientMutation = {
  deleteClient:  {
    __typename: "Client",
    id: string,
    clientNumber: string,
    name: string,
    contact: string,
    phone: string,
    address: string,
    province: string | null,
    city: string,
    postalCode: string,
    email: string,
    owners: Array< string | null > | null,
    status: string | null,
    contracts:  {
      __typename: "ModelContractConnection",
      items:  Array< {
        __typename: "Contract",
        clientID: string,
        type: string,
        startDate: string | null,
        endDate: string | null,
        gst: string | null,
        qst: string | null,
        period: string | null,
        corporation: boolean | null,
        corporationYearEndDate: string | null,
        payrollNumber: string | null,
        payrollFrequency: string | null,
        remittancePeriod: string | null,
        remittancePeriodQc: string | null,
        cheques: number | null,
        wsib: string | null,
        wsibRemittance: string | null,
        wsibRate: string | null,
        wsibCode: string | null,
        csst: string | null,
        csstRemittance: string | null,
        csstRate: string | null,
        csstCode: string | null,
        t4Deadline: string | null,
        createdAt: string,
        updatedAt: string,
        version: number,
      } | null > | null,
      nextToken: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
    version: number,
  } | null,
};

export type CreateContractMutationVariables = {
  input: CreateContractInput,
  condition?: ModelContractConditionInput | null,
};

export type CreateContractMutation = {
  createContract:  {
    __typename: "Contract",
    clientID: string,
    client:  {
      __typename: "Client",
      id: string,
      clientNumber: string,
      name: string,
      contact: string,
      phone: string,
      address: string,
      province: string | null,
      city: string,
      postalCode: string,
      email: string,
      owners: Array< string | null > | null,
      status: string | null,
      contracts:  {
        __typename: "ModelContractConnection",
        nextToken: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      version: number,
    } | null,
    type: string,
    startDate: string | null,
    endDate: string | null,
    gst: string | null,
    qst: string | null,
    period: string | null,
    corporation: boolean | null,
    corporationYearEndDate: string | null,
    payrollNumber: string | null,
    payrollFrequency: string | null,
    remittancePeriod: string | null,
    remittancePeriodQc: string | null,
    cheques: number | null,
    wsib: string | null,
    wsibRemittance: string | null,
    wsibRate: string | null,
    wsibCode: string | null,
    csst: string | null,
    csstRemittance: string | null,
    csstRate: string | null,
    csstCode: string | null,
    t4Deadline: string | null,
    jobs:  {
      __typename: "ModelJobConnection",
      items:  Array< {
        __typename: "Job",
        id: string,
        clientID: string,
        type: string,
        deadline: string,
        assigneeID: string | null,
        createdAt: string,
        updatedAt: string,
        version: number,
      } | null > | null,
      nextToken: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
    version: number,
  } | null,
};

export type UpdateContractMutationVariables = {
  input: UpdateContractInput,
  condition?: ModelContractConditionInput | null,
};

export type UpdateContractMutation = {
  updateContract:  {
    __typename: "Contract",
    clientID: string,
    client:  {
      __typename: "Client",
      id: string,
      clientNumber: string,
      name: string,
      contact: string,
      phone: string,
      address: string,
      province: string | null,
      city: string,
      postalCode: string,
      email: string,
      owners: Array< string | null > | null,
      status: string | null,
      contracts:  {
        __typename: "ModelContractConnection",
        nextToken: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      version: number,
    } | null,
    type: string,
    startDate: string | null,
    endDate: string | null,
    gst: string | null,
    qst: string | null,
    period: string | null,
    corporation: boolean | null,
    corporationYearEndDate: string | null,
    payrollNumber: string | null,
    payrollFrequency: string | null,
    remittancePeriod: string | null,
    remittancePeriodQc: string | null,
    cheques: number | null,
    wsib: string | null,
    wsibRemittance: string | null,
    wsibRate: string | null,
    wsibCode: string | null,
    csst: string | null,
    csstRemittance: string | null,
    csstRate: string | null,
    csstCode: string | null,
    t4Deadline: string | null,
    jobs:  {
      __typename: "ModelJobConnection",
      items:  Array< {
        __typename: "Job",
        id: string,
        clientID: string,
        type: string,
        deadline: string,
        assigneeID: string | null,
        createdAt: string,
        updatedAt: string,
        version: number,
      } | null > | null,
      nextToken: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
    version: number,
  } | null,
};

export type DeleteContractMutationVariables = {
  input: DeleteContractInput,
  condition?: ModelContractConditionInput | null,
};

export type DeleteContractMutation = {
  deleteContract:  {
    __typename: "Contract",
    clientID: string,
    client:  {
      __typename: "Client",
      id: string,
      clientNumber: string,
      name: string,
      contact: string,
      phone: string,
      address: string,
      province: string | null,
      city: string,
      postalCode: string,
      email: string,
      owners: Array< string | null > | null,
      status: string | null,
      contracts:  {
        __typename: "ModelContractConnection",
        nextToken: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      version: number,
    } | null,
    type: string,
    startDate: string | null,
    endDate: string | null,
    gst: string | null,
    qst: string | null,
    period: string | null,
    corporation: boolean | null,
    corporationYearEndDate: string | null,
    payrollNumber: string | null,
    payrollFrequency: string | null,
    remittancePeriod: string | null,
    remittancePeriodQc: string | null,
    cheques: number | null,
    wsib: string | null,
    wsibRemittance: string | null,
    wsibRate: string | null,
    wsibCode: string | null,
    csst: string | null,
    csstRemittance: string | null,
    csstRate: string | null,
    csstCode: string | null,
    t4Deadline: string | null,
    jobs:  {
      __typename: "ModelJobConnection",
      items:  Array< {
        __typename: "Job",
        id: string,
        clientID: string,
        type: string,
        deadline: string,
        assigneeID: string | null,
        createdAt: string,
        updatedAt: string,
        version: number,
      } | null > | null,
      nextToken: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
    version: number,
  } | null,
};

export type CreateJobMutationVariables = {
  input: CreateJobInput,
  condition?: ModelJobConditionInput | null,
};

export type CreateJobMutation = {
  createJob:  {
    __typename: "Job",
    id: string,
    clientID: string,
    type: string,
    contract:  {
      __typename: "Contract",
      clientID: string,
      client:  {
        __typename: "Client",
        id: string,
        clientNumber: string,
        name: string,
        contact: string,
        phone: string,
        address: string,
        province: string | null,
        city: string,
        postalCode: string,
        email: string,
        owners: Array< string | null > | null,
        status: string | null,
        createdAt: string,
        updatedAt: string,
        version: number,
      } | null,
      type: string,
      startDate: string | null,
      endDate: string | null,
      gst: string | null,
      qst: string | null,
      period: string | null,
      corporation: boolean | null,
      corporationYearEndDate: string | null,
      payrollNumber: string | null,
      payrollFrequency: string | null,
      remittancePeriod: string | null,
      remittancePeriodQc: string | null,
      cheques: number | null,
      wsib: string | null,
      wsibRemittance: string | null,
      wsibRate: string | null,
      wsibCode: string | null,
      csst: string | null,
      csstRemittance: string | null,
      csstRate: string | null,
      csstCode: string | null,
      t4Deadline: string | null,
      jobs:  {
        __typename: "ModelJobConnection",
        nextToken: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      version: number,
    } | null,
    deadline: string,
    assigneeID: string | null,
    createdAt: string,
    updatedAt: string,
    version: number,
  } | null,
};

export type UpdateJobMutationVariables = {
  input: UpdateJobInput,
  condition?: ModelJobConditionInput | null,
};

export type UpdateJobMutation = {
  updateJob:  {
    __typename: "Job",
    id: string,
    clientID: string,
    type: string,
    contract:  {
      __typename: "Contract",
      clientID: string,
      client:  {
        __typename: "Client",
        id: string,
        clientNumber: string,
        name: string,
        contact: string,
        phone: string,
        address: string,
        province: string | null,
        city: string,
        postalCode: string,
        email: string,
        owners: Array< string | null > | null,
        status: string | null,
        createdAt: string,
        updatedAt: string,
        version: number,
      } | null,
      type: string,
      startDate: string | null,
      endDate: string | null,
      gst: string | null,
      qst: string | null,
      period: string | null,
      corporation: boolean | null,
      corporationYearEndDate: string | null,
      payrollNumber: string | null,
      payrollFrequency: string | null,
      remittancePeriod: string | null,
      remittancePeriodQc: string | null,
      cheques: number | null,
      wsib: string | null,
      wsibRemittance: string | null,
      wsibRate: string | null,
      wsibCode: string | null,
      csst: string | null,
      csstRemittance: string | null,
      csstRate: string | null,
      csstCode: string | null,
      t4Deadline: string | null,
      jobs:  {
        __typename: "ModelJobConnection",
        nextToken: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      version: number,
    } | null,
    deadline: string,
    assigneeID: string | null,
    createdAt: string,
    updatedAt: string,
    version: number,
  } | null,
};

export type DeleteJobMutationVariables = {
  input: DeleteJobInput,
  condition?: ModelJobConditionInput | null,
};

export type DeleteJobMutation = {
  deleteJob:  {
    __typename: "Job",
    id: string,
    clientID: string,
    type: string,
    contract:  {
      __typename: "Contract",
      clientID: string,
      client:  {
        __typename: "Client",
        id: string,
        clientNumber: string,
        name: string,
        contact: string,
        phone: string,
        address: string,
        province: string | null,
        city: string,
        postalCode: string,
        email: string,
        owners: Array< string | null > | null,
        status: string | null,
        createdAt: string,
        updatedAt: string,
        version: number,
      } | null,
      type: string,
      startDate: string | null,
      endDate: string | null,
      gst: string | null,
      qst: string | null,
      period: string | null,
      corporation: boolean | null,
      corporationYearEndDate: string | null,
      payrollNumber: string | null,
      payrollFrequency: string | null,
      remittancePeriod: string | null,
      remittancePeriodQc: string | null,
      cheques: number | null,
      wsib: string | null,
      wsibRemittance: string | null,
      wsibRate: string | null,
      wsibCode: string | null,
      csst: string | null,
      csstRemittance: string | null,
      csstRate: string | null,
      csstCode: string | null,
      t4Deadline: string | null,
      jobs:  {
        __typename: "ModelJobConnection",
        nextToken: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      version: number,
    } | null,
    deadline: string,
    assigneeID: string | null,
    createdAt: string,
    updatedAt: string,
    version: number,
  } | null,
};

export type GetUserQueryVariables = {
  id: string,
};

export type GetUserQuery = {
  getUser:  {
    __typename: "User",
    id: string,
    email: string,
    firstName: string,
    lastName: string,
    phone: string,
    role: UserRole,
    status: UserStatus,
    createdAt: string,
    updatedAt: string,
    version: number,
  } | null,
};

export type ListUsersQueryVariables = {
  filter?: ModelUserFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListUsersQuery = {
  listUsers:  {
    __typename: "ModelUserConnection",
    items:  Array< {
      __typename: "User",
      id: string,
      email: string,
      firstName: string,
      lastName: string,
      phone: string,
      role: UserRole,
      status: UserStatus,
      createdAt: string,
      updatedAt: string,
      version: number,
    } | null > | null,
    nextToken: string | null,
  } | null,
};

export type GetClientQueryVariables = {
  id: string,
};

export type GetClientQuery = {
  getClient:  {
    __typename: "Client",
    id: string,
    clientNumber: string,
    name: string,
    contact: string,
    phone: string,
    address: string,
    province: string | null,
    city: string,
    postalCode: string,
    email: string,
    owners: Array< string | null > | null,
    status: string | null,
    contracts:  {
      __typename: "ModelContractConnection",
      items:  Array< {
        __typename: "Contract",
        clientID: string,
        type: string,
        startDate: string | null,
        endDate: string | null,
        gst: string | null,
        qst: string | null,
        period: string | null,
        corporation: boolean | null,
        corporationYearEndDate: string | null,
        payrollNumber: string | null,
        payrollFrequency: string | null,
        remittancePeriod: string | null,
        remittancePeriodQc: string | null,
        cheques: number | null,
        wsib: string | null,
        wsibRemittance: string | null,
        wsibRate: string | null,
        wsibCode: string | null,
        csst: string | null,
        csstRemittance: string | null,
        csstRate: string | null,
        csstCode: string | null,
        t4Deadline: string | null,
        createdAt: string,
        updatedAt: string,
        version: number,
      } | null > | null,
      nextToken: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
    version: number,
  } | null,
};

export type ListClientsQueryVariables = {
  filter?: ModelClientFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListClientsQuery = {
  listClients:  {
    __typename: "ModelClientConnection",
    items:  Array< {
      __typename: "Client",
      id: string,
      clientNumber: string,
      name: string,
      contact: string,
      phone: string,
      address: string,
      province: string | null,
      city: string,
      postalCode: string,
      email: string,
      owners: Array< string | null > | null,
      status: string | null,
      contracts:  {
        __typename: "ModelContractConnection",
        nextToken: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      version: number,
    } | null > | null,
    nextToken: string | null,
  } | null,
};

export type GetContractQueryVariables = {
  clientID: string,
  type: string,
};

export type GetContractQuery = {
  getContract:  {
    __typename: "Contract",
    clientID: string,
    client:  {
      __typename: "Client",
      id: string,
      clientNumber: string,
      name: string,
      contact: string,
      phone: string,
      address: string,
      province: string | null,
      city: string,
      postalCode: string,
      email: string,
      owners: Array< string | null > | null,
      status: string | null,
      contracts:  {
        __typename: "ModelContractConnection",
        nextToken: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      version: number,
    } | null,
    type: string,
    startDate: string | null,
    endDate: string | null,
    gst: string | null,
    qst: string | null,
    period: string | null,
    corporation: boolean | null,
    corporationYearEndDate: string | null,
    payrollNumber: string | null,
    payrollFrequency: string | null,
    remittancePeriod: string | null,
    remittancePeriodQc: string | null,
    cheques: number | null,
    wsib: string | null,
    wsibRemittance: string | null,
    wsibRate: string | null,
    wsibCode: string | null,
    csst: string | null,
    csstRemittance: string | null,
    csstRate: string | null,
    csstCode: string | null,
    t4Deadline: string | null,
    jobs:  {
      __typename: "ModelJobConnection",
      items:  Array< {
        __typename: "Job",
        id: string,
        clientID: string,
        type: string,
        deadline: string,
        assigneeID: string | null,
        createdAt: string,
        updatedAt: string,
        version: number,
      } | null > | null,
      nextToken: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
    version: number,
  } | null,
};

export type ListContractsQueryVariables = {
  clientID?: string | null,
  type?: ModelStringKeyConditionInput | null,
  filter?: ModelContractFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
  sortDirection?: ModelSortDirection | null,
};

export type ListContractsQuery = {
  listContracts:  {
    __typename: "ModelContractConnection",
    items:  Array< {
      __typename: "Contract",
      clientID: string,
      client:  {
        __typename: "Client",
        id: string,
        clientNumber: string,
        name: string,
        contact: string,
        phone: string,
        address: string,
        province: string | null,
        city: string,
        postalCode: string,
        email: string,
        owners: Array< string | null > | null,
        status: string | null,
        createdAt: string,
        updatedAt: string,
        version: number,
      } | null,
      type: string,
      startDate: string | null,
      endDate: string | null,
      gst: string | null,
      qst: string | null,
      period: string | null,
      corporation: boolean | null,
      corporationYearEndDate: string | null,
      payrollNumber: string | null,
      payrollFrequency: string | null,
      remittancePeriod: string | null,
      remittancePeriodQc: string | null,
      cheques: number | null,
      wsib: string | null,
      wsibRemittance: string | null,
      wsibRate: string | null,
      wsibCode: string | null,
      csst: string | null,
      csstRemittance: string | null,
      csstRate: string | null,
      csstCode: string | null,
      t4Deadline: string | null,
      jobs:  {
        __typename: "ModelJobConnection",
        nextToken: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      version: number,
    } | null > | null,
    nextToken: string | null,
  } | null,
};

export type GetJobQueryVariables = {
  id: string,
};

export type GetJobQuery = {
  getJob:  {
    __typename: "Job",
    id: string,
    clientID: string,
    type: string,
    contract:  {
      __typename: "Contract",
      clientID: string,
      client:  {
        __typename: "Client",
        id: string,
        clientNumber: string,
        name: string,
        contact: string,
        phone: string,
        address: string,
        province: string | null,
        city: string,
        postalCode: string,
        email: string,
        owners: Array< string | null > | null,
        status: string | null,
        createdAt: string,
        updatedAt: string,
        version: number,
      } | null,
      type: string,
      startDate: string | null,
      endDate: string | null,
      gst: string | null,
      qst: string | null,
      period: string | null,
      corporation: boolean | null,
      corporationYearEndDate: string | null,
      payrollNumber: string | null,
      payrollFrequency: string | null,
      remittancePeriod: string | null,
      remittancePeriodQc: string | null,
      cheques: number | null,
      wsib: string | null,
      wsibRemittance: string | null,
      wsibRate: string | null,
      wsibCode: string | null,
      csst: string | null,
      csstRemittance: string | null,
      csstRate: string | null,
      csstCode: string | null,
      t4Deadline: string | null,
      jobs:  {
        __typename: "ModelJobConnection",
        nextToken: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      version: number,
    } | null,
    deadline: string,
    assigneeID: string | null,
    createdAt: string,
    updatedAt: string,
    version: number,
  } | null,
};

export type ListJobsQueryVariables = {
  filter?: ModelJobFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListJobsQuery = {
  listJobs:  {
    __typename: "ModelJobConnection",
    items:  Array< {
      __typename: "Job",
      id: string,
      clientID: string,
      type: string,
      contract:  {
        __typename: "Contract",
        clientID: string,
        type: string,
        startDate: string | null,
        endDate: string | null,
        gst: string | null,
        qst: string | null,
        period: string | null,
        corporation: boolean | null,
        corporationYearEndDate: string | null,
        payrollNumber: string | null,
        payrollFrequency: string | null,
        remittancePeriod: string | null,
        remittancePeriodQc: string | null,
        cheques: number | null,
        wsib: string | null,
        wsibRemittance: string | null,
        wsibRate: string | null,
        wsibCode: string | null,
        csst: string | null,
        csstRemittance: string | null,
        csstRate: string | null,
        csstCode: string | null,
        t4Deadline: string | null,
        createdAt: string,
        updatedAt: string,
        version: number,
      } | null,
      deadline: string,
      assigneeID: string | null,
      createdAt: string,
      updatedAt: string,
      version: number,
    } | null > | null,
    nextToken: string | null,
  } | null,
};

export type OnCreateUserSubscription = {
  onCreateUser:  {
    __typename: "User",
    id: string,
    email: string,
    firstName: string,
    lastName: string,
    phone: string,
    role: UserRole,
    status: UserStatus,
    createdAt: string,
    updatedAt: string,
    version: number,
  } | null,
};

export type OnUpdateUserSubscription = {
  onUpdateUser:  {
    __typename: "User",
    id: string,
    email: string,
    firstName: string,
    lastName: string,
    phone: string,
    role: UserRole,
    status: UserStatus,
    createdAt: string,
    updatedAt: string,
    version: number,
  } | null,
};

export type OnDeleteUserSubscription = {
  onDeleteUser:  {
    __typename: "User",
    id: string,
    email: string,
    firstName: string,
    lastName: string,
    phone: string,
    role: UserRole,
    status: UserStatus,
    createdAt: string,
    updatedAt: string,
    version: number,
  } | null,
};

export type OnCreateClientSubscription = {
  onCreateClient:  {
    __typename: "Client",
    id: string,
    clientNumber: string,
    name: string,
    contact: string,
    phone: string,
    address: string,
    province: string | null,
    city: string,
    postalCode: string,
    email: string,
    owners: Array< string | null > | null,
    status: string | null,
    contracts:  {
      __typename: "ModelContractConnection",
      items:  Array< {
        __typename: "Contract",
        clientID: string,
        type: string,
        startDate: string | null,
        endDate: string | null,
        gst: string | null,
        qst: string | null,
        period: string | null,
        corporation: boolean | null,
        corporationYearEndDate: string | null,
        payrollNumber: string | null,
        payrollFrequency: string | null,
        remittancePeriod: string | null,
        remittancePeriodQc: string | null,
        cheques: number | null,
        wsib: string | null,
        wsibRemittance: string | null,
        wsibRate: string | null,
        wsibCode: string | null,
        csst: string | null,
        csstRemittance: string | null,
        csstRate: string | null,
        csstCode: string | null,
        t4Deadline: string | null,
        createdAt: string,
        updatedAt: string,
        version: number,
      } | null > | null,
      nextToken: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
    version: number,
  } | null,
};

export type OnUpdateClientSubscription = {
  onUpdateClient:  {
    __typename: "Client",
    id: string,
    clientNumber: string,
    name: string,
    contact: string,
    phone: string,
    address: string,
    province: string | null,
    city: string,
    postalCode: string,
    email: string,
    owners: Array< string | null > | null,
    status: string | null,
    contracts:  {
      __typename: "ModelContractConnection",
      items:  Array< {
        __typename: "Contract",
        clientID: string,
        type: string,
        startDate: string | null,
        endDate: string | null,
        gst: string | null,
        qst: string | null,
        period: string | null,
        corporation: boolean | null,
        corporationYearEndDate: string | null,
        payrollNumber: string | null,
        payrollFrequency: string | null,
        remittancePeriod: string | null,
        remittancePeriodQc: string | null,
        cheques: number | null,
        wsib: string | null,
        wsibRemittance: string | null,
        wsibRate: string | null,
        wsibCode: string | null,
        csst: string | null,
        csstRemittance: string | null,
        csstRate: string | null,
        csstCode: string | null,
        t4Deadline: string | null,
        createdAt: string,
        updatedAt: string,
        version: number,
      } | null > | null,
      nextToken: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
    version: number,
  } | null,
};

export type OnDeleteClientSubscription = {
  onDeleteClient:  {
    __typename: "Client",
    id: string,
    clientNumber: string,
    name: string,
    contact: string,
    phone: string,
    address: string,
    province: string | null,
    city: string,
    postalCode: string,
    email: string,
    owners: Array< string | null > | null,
    status: string | null,
    contracts:  {
      __typename: "ModelContractConnection",
      items:  Array< {
        __typename: "Contract",
        clientID: string,
        type: string,
        startDate: string | null,
        endDate: string | null,
        gst: string | null,
        qst: string | null,
        period: string | null,
        corporation: boolean | null,
        corporationYearEndDate: string | null,
        payrollNumber: string | null,
        payrollFrequency: string | null,
        remittancePeriod: string | null,
        remittancePeriodQc: string | null,
        cheques: number | null,
        wsib: string | null,
        wsibRemittance: string | null,
        wsibRate: string | null,
        wsibCode: string | null,
        csst: string | null,
        csstRemittance: string | null,
        csstRate: string | null,
        csstCode: string | null,
        t4Deadline: string | null,
        createdAt: string,
        updatedAt: string,
        version: number,
      } | null > | null,
      nextToken: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
    version: number,
  } | null,
};

export type OnCreateContractSubscription = {
  onCreateContract:  {
    __typename: "Contract",
    clientID: string,
    client:  {
      __typename: "Client",
      id: string,
      clientNumber: string,
      name: string,
      contact: string,
      phone: string,
      address: string,
      province: string | null,
      city: string,
      postalCode: string,
      email: string,
      owners: Array< string | null > | null,
      status: string | null,
      contracts:  {
        __typename: "ModelContractConnection",
        nextToken: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      version: number,
    } | null,
    type: string,
    startDate: string | null,
    endDate: string | null,
    gst: string | null,
    qst: string | null,
    period: string | null,
    corporation: boolean | null,
    corporationYearEndDate: string | null,
    payrollNumber: string | null,
    payrollFrequency: string | null,
    remittancePeriod: string | null,
    remittancePeriodQc: string | null,
    cheques: number | null,
    wsib: string | null,
    wsibRemittance: string | null,
    wsibRate: string | null,
    wsibCode: string | null,
    csst: string | null,
    csstRemittance: string | null,
    csstRate: string | null,
    csstCode: string | null,
    t4Deadline: string | null,
    jobs:  {
      __typename: "ModelJobConnection",
      items:  Array< {
        __typename: "Job",
        id: string,
        clientID: string,
        type: string,
        deadline: string,
        assigneeID: string | null,
        createdAt: string,
        updatedAt: string,
        version: number,
      } | null > | null,
      nextToken: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
    version: number,
  } | null,
};

export type OnUpdateContractSubscription = {
  onUpdateContract:  {
    __typename: "Contract",
    clientID: string,
    client:  {
      __typename: "Client",
      id: string,
      clientNumber: string,
      name: string,
      contact: string,
      phone: string,
      address: string,
      province: string | null,
      city: string,
      postalCode: string,
      email: string,
      owners: Array< string | null > | null,
      status: string | null,
      contracts:  {
        __typename: "ModelContractConnection",
        nextToken: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      version: number,
    } | null,
    type: string,
    startDate: string | null,
    endDate: string | null,
    gst: string | null,
    qst: string | null,
    period: string | null,
    corporation: boolean | null,
    corporationYearEndDate: string | null,
    payrollNumber: string | null,
    payrollFrequency: string | null,
    remittancePeriod: string | null,
    remittancePeriodQc: string | null,
    cheques: number | null,
    wsib: string | null,
    wsibRemittance: string | null,
    wsibRate: string | null,
    wsibCode: string | null,
    csst: string | null,
    csstRemittance: string | null,
    csstRate: string | null,
    csstCode: string | null,
    t4Deadline: string | null,
    jobs:  {
      __typename: "ModelJobConnection",
      items:  Array< {
        __typename: "Job",
        id: string,
        clientID: string,
        type: string,
        deadline: string,
        assigneeID: string | null,
        createdAt: string,
        updatedAt: string,
        version: number,
      } | null > | null,
      nextToken: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
    version: number,
  } | null,
};

export type OnDeleteContractSubscription = {
  onDeleteContract:  {
    __typename: "Contract",
    clientID: string,
    client:  {
      __typename: "Client",
      id: string,
      clientNumber: string,
      name: string,
      contact: string,
      phone: string,
      address: string,
      province: string | null,
      city: string,
      postalCode: string,
      email: string,
      owners: Array< string | null > | null,
      status: string | null,
      contracts:  {
        __typename: "ModelContractConnection",
        nextToken: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      version: number,
    } | null,
    type: string,
    startDate: string | null,
    endDate: string | null,
    gst: string | null,
    qst: string | null,
    period: string | null,
    corporation: boolean | null,
    corporationYearEndDate: string | null,
    payrollNumber: string | null,
    payrollFrequency: string | null,
    remittancePeriod: string | null,
    remittancePeriodQc: string | null,
    cheques: number | null,
    wsib: string | null,
    wsibRemittance: string | null,
    wsibRate: string | null,
    wsibCode: string | null,
    csst: string | null,
    csstRemittance: string | null,
    csstRate: string | null,
    csstCode: string | null,
    t4Deadline: string | null,
    jobs:  {
      __typename: "ModelJobConnection",
      items:  Array< {
        __typename: "Job",
        id: string,
        clientID: string,
        type: string,
        deadline: string,
        assigneeID: string | null,
        createdAt: string,
        updatedAt: string,
        version: number,
      } | null > | null,
      nextToken: string | null,
    } | null,
    createdAt: string,
    updatedAt: string,
    version: number,
  } | null,
};

export type OnCreateJobSubscription = {
  onCreateJob:  {
    __typename: "Job",
    id: string,
    clientID: string,
    type: string,
    contract:  {
      __typename: "Contract",
      clientID: string,
      client:  {
        __typename: "Client",
        id: string,
        clientNumber: string,
        name: string,
        contact: string,
        phone: string,
        address: string,
        province: string | null,
        city: string,
        postalCode: string,
        email: string,
        owners: Array< string | null > | null,
        status: string | null,
        createdAt: string,
        updatedAt: string,
        version: number,
      } | null,
      type: string,
      startDate: string | null,
      endDate: string | null,
      gst: string | null,
      qst: string | null,
      period: string | null,
      corporation: boolean | null,
      corporationYearEndDate: string | null,
      payrollNumber: string | null,
      payrollFrequency: string | null,
      remittancePeriod: string | null,
      remittancePeriodQc: string | null,
      cheques: number | null,
      wsib: string | null,
      wsibRemittance: string | null,
      wsibRate: string | null,
      wsibCode: string | null,
      csst: string | null,
      csstRemittance: string | null,
      csstRate: string | null,
      csstCode: string | null,
      t4Deadline: string | null,
      jobs:  {
        __typename: "ModelJobConnection",
        nextToken: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      version: number,
    } | null,
    deadline: string,
    assigneeID: string | null,
    createdAt: string,
    updatedAt: string,
    version: number,
  } | null,
};

export type OnUpdateJobSubscription = {
  onUpdateJob:  {
    __typename: "Job",
    id: string,
    clientID: string,
    type: string,
    contract:  {
      __typename: "Contract",
      clientID: string,
      client:  {
        __typename: "Client",
        id: string,
        clientNumber: string,
        name: string,
        contact: string,
        phone: string,
        address: string,
        province: string | null,
        city: string,
        postalCode: string,
        email: string,
        owners: Array< string | null > | null,
        status: string | null,
        createdAt: string,
        updatedAt: string,
        version: number,
      } | null,
      type: string,
      startDate: string | null,
      endDate: string | null,
      gst: string | null,
      qst: string | null,
      period: string | null,
      corporation: boolean | null,
      corporationYearEndDate: string | null,
      payrollNumber: string | null,
      payrollFrequency: string | null,
      remittancePeriod: string | null,
      remittancePeriodQc: string | null,
      cheques: number | null,
      wsib: string | null,
      wsibRemittance: string | null,
      wsibRate: string | null,
      wsibCode: string | null,
      csst: string | null,
      csstRemittance: string | null,
      csstRate: string | null,
      csstCode: string | null,
      t4Deadline: string | null,
      jobs:  {
        __typename: "ModelJobConnection",
        nextToken: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      version: number,
    } | null,
    deadline: string,
    assigneeID: string | null,
    createdAt: string,
    updatedAt: string,
    version: number,
  } | null,
};

export type OnDeleteJobSubscription = {
  onDeleteJob:  {
    __typename: "Job",
    id: string,
    clientID: string,
    type: string,
    contract:  {
      __typename: "Contract",
      clientID: string,
      client:  {
        __typename: "Client",
        id: string,
        clientNumber: string,
        name: string,
        contact: string,
        phone: string,
        address: string,
        province: string | null,
        city: string,
        postalCode: string,
        email: string,
        owners: Array< string | null > | null,
        status: string | null,
        createdAt: string,
        updatedAt: string,
        version: number,
      } | null,
      type: string,
      startDate: string | null,
      endDate: string | null,
      gst: string | null,
      qst: string | null,
      period: string | null,
      corporation: boolean | null,
      corporationYearEndDate: string | null,
      payrollNumber: string | null,
      payrollFrequency: string | null,
      remittancePeriod: string | null,
      remittancePeriodQc: string | null,
      cheques: number | null,
      wsib: string | null,
      wsibRemittance: string | null,
      wsibRate: string | null,
      wsibCode: string | null,
      csst: string | null,
      csstRemittance: string | null,
      csstRate: string | null,
      csstCode: string | null,
      t4Deadline: string | null,
      jobs:  {
        __typename: "ModelJobConnection",
        nextToken: string | null,
      } | null,
      createdAt: string,
      updatedAt: string,
      version: number,
    } | null,
    deadline: string,
    assigneeID: string | null,
    createdAt: string,
    updatedAt: string,
    version: number,
  } | null,
};
